// <auto-generated />
using System;
using Lab5;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250829083809_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Lab5.Models.ChungChi", b =>
                {
                    b.Property<string>("MaChungChi")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaChungChi");

                    b.Property<decimal?>("DiemTongKet")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("DiemTongKet");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("GhiChu");

                    b.Property<string>("HocVienMaHocVien")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaHocVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaHocVien");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaMonHoc");

                    b.Property<string>("MonHocMaMonHoc")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("date")
                        .HasColumnName("NgayCap");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("SoSeri")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("SoSeri");

                    b.Property<short>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("TrangThai");

                    b.Property<short?>("XepLoai")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasColumnName("XepLoai");

                    b.HasKey("MaChungChi");

                    b.HasIndex("HocVienMaHocVien");

                    b.HasIndex("MonHocMaMonHoc");

                    b.HasIndex("NgayCap")
                        .HasDatabaseName("idx_chungchi_ngaycap");

                    b.HasIndex("SoSeri")
                        .IsUnique()
                        .HasDatabaseName("idx_chungchi_soseri");

                    b.HasIndex("MaHocVien", "MaMonHoc")
                        .IsUnique()
                        .HasDatabaseName("uk_chungchi_hocvien_monhoc");

                    b.ToTable("chungchi");
                });

            modelBuilder.Entity("Lab5.Models.DangKy", b =>
                {
                    b.Property<string>("MaDangKy")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaDangKy");

                    b.Property<string>("BienLai")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("BienLai");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("GhiChu");

                    b.Property<string>("MaHocVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaHocVien");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaLop");

                    b.Property<DateTime>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("NgayDangKy")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("SoTienDong")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("SoTienDong");

                    b.Property<short>("TrangThaiDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("TrangThaiDong");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHocVien")
                        .HasDatabaseName("idx_dangky_hocvien");

                    b.HasIndex("MaLop")
                        .HasDatabaseName("idx_dangky_lop");

                    b.HasIndex("MaHocVien", "MaLop")
                        .IsUnique()
                        .HasDatabaseName("uk_dangky_hocvien_lop");

                    b.ToTable("dangky");
                });

            modelBuilder.Entity("Lab5.Models.Day", b =>
                {
                    b.Property<string>("MaGiaoVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaGiaoVien")
                        .HasColumnOrder(0);

                    b.Property<string>("MaLop")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaLop")
                        .HasColumnOrder(1);

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("GhiChu");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("NgayKetThuc");

                    b.Property<int>("SoTietDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SoTietDay");

                    b.HasKey("MaGiaoVien", "MaLop");

                    b.HasIndex("MaLop");

                    b.ToTable("day");
                });

            modelBuilder.Entity("Lab5.Models.Diem", b =>
                {
                    b.Property<string>("MaDiem")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaDiem");

                    b.Property<decimal?>("DiemLyThuyet")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("DiemLyThuyet");

                    b.Property<decimal?>("DiemThucHanh")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("DiemThucHanh");

                    b.Property<decimal?>("DiemTrungBinh")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("DiemTrungBinh");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("GhiChu");

                    b.Property<string>("HocVienMaHocVien")
                        .HasColumnType("varchar(10)");

                    b.Property<short?>("KetQua")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasColumnName("KetQua");

                    b.Property<int>("LanThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("LanThi");

                    b.Property<string>("MaHocVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaHocVien");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaMonHoc");

                    b.Property<string>("MonHocMaMonHoc")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("NgayNhap")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("NgayThi")
                        .HasColumnType("date")
                        .HasColumnName("NgayThi");

                    b.HasKey("MaDiem");

                    b.HasIndex("HocVienMaHocVien");

                    b.HasIndex("MaHocVien")
                        .HasDatabaseName("idx_diem_hocvien");

                    b.HasIndex("MaMonHoc")
                        .HasDatabaseName("idx_diem_monhoc");

                    b.HasIndex("MonHocMaMonHoc");

                    b.HasIndex("NgayThi")
                        .HasDatabaseName("idx_diem_ngaythi");

                    b.HasIndex("MaHocVien", "MaMonHoc", "LanThi")
                        .IsUnique()
                        .HasDatabaseName("uk_diem_hocvien_monhoc_lanthi");

                    b.ToTable("diem");
                });

            modelBuilder.Entity("Lab5.Models.GiaoVien", b =>
                {
                    b.Property<string>("MaGiaoVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaGiaoVien");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("ChuyenMon");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("DiaChi");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("DienThoai");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<short?>("GioiTinh")
                        .HasColumnType("smallint")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("HoTen");

                    b.Property<short>("KinhNghiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("KinhNghiem");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("NoiCongTac")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("NoiCongTac");

                    b.HasKey("MaGiaoVien");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_giaovien_email");

                    b.HasIndex("HoTen")
                        .HasDatabaseName("idx_giaovien_hoten");

                    b.ToTable("giaovien");
                });

            modelBuilder.Entity("Lab5.Models.Hoc", b =>
                {
                    b.Property<string>("MaHocVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaHocVien")
                        .HasColumnOrder(0);

                    b.Property<string>("MaMonHoc")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaMonHoc")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("NgayBatDauHoc")
                        .HasColumnType("date")
                        .HasColumnName("NgayBatDauHoc");

                    b.Property<DateTime?>("NgayKetThucHoc")
                        .HasColumnType("date")
                        .HasColumnName("NgayKetThucHoc");

                    b.Property<short>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("TrangThai");

                    b.HasKey("MaHocVien", "MaMonHoc");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("hoc");
                });

            modelBuilder.Entity("Lab5.Models.HocVien", b =>
                {
                    b.Property<string>("MaHocVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaHocVien");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("DiaChi");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("DienThoai");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<short?>("GioiTinh")
                        .HasColumnType("smallint")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("HoTen");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayDangKy");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("QueQuan");

                    b.Property<short>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("TrangThai");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("TrinhDo");

                    b.HasKey("MaHocVien");

                    b.HasIndex("DienThoai")
                        .HasDatabaseName("idx_hocvien_dienthoai");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_hocvien_email");

                    b.HasIndex("HoTen")
                        .HasDatabaseName("idx_hocvien_hoten");

                    b.ToTable("hocvien");
                });

            modelBuilder.Entity("Lab5.Models.KhoaHoc", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaKhoaHoc");

                    b.Property<DateTime>("NgayKhaiGiang")
                        .HasColumnType("date")
                        .HasColumnName("NgayKhaiGiang");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TenKhoaHoc")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("TenKhoaHoc");

                    b.Property<short>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("TrangThai");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("khoahoc");
                });

            modelBuilder.Entity("Lab5.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaLop");

                    b.Property<string>("MaGiaoVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaGiaoVien");

                    b.Property<string>("MaKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaKhoaHoc");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaMonHoc");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("NgayKetThuc");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("PhongHoc");

                    b.Property<int>("SoHocVienDuKien")
                        .HasColumnType("int")
                        .HasColumnName("SoHocVienDuKien");

                    b.Property<int>("SoHocVienThucTe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SoHocVienThucTe");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("TenLop");

                    b.Property<string>("ThoiGianHoc")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ThoiGianHoc");

                    b.Property<short>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("TrangThai");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGiaoVien")
                        .HasDatabaseName("idx_lophoc_giaovien");

                    b.HasIndex("MaKhoaHoc")
                        .HasDatabaseName("idx_lophoc_khoahoc");

                    b.HasIndex("MaMonHoc")
                        .HasDatabaseName("idx_lophoc_monhoc");

                    b.ToTable("lophoc");
                });

            modelBuilder.Entity("Lab5.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMonHoc")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaMonHoc");

                    b.Property<short>("CapDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("CapDo");

                    b.Property<decimal?>("HocPhi")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("HocPhi");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("MoTa");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int")
                        .HasColumnName("SoTiet");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("TenMonHoc");

                    b.HasKey("MaMonHoc");

                    b.ToTable("monhoc");
                });

            modelBuilder.Entity("Lab5.Models.ChungChi", b =>
                {
                    b.HasOne("Lab5.Models.HocVien", null)
                        .WithMany("DanhSachChungChi")
                        .HasForeignKey("HocVienMaHocVien");

                    b.HasOne("Lab5.Models.MonHoc", null)
                        .WithMany("DanhSachChungChi")
                        .HasForeignKey("MonHocMaMonHoc");

                    b.HasOne("Lab5.Models.Hoc", "Hoc")
                        .WithMany("DanhSachChungChi")
                        .HasForeignKey("MaHocVien", "MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoc");
                });

            modelBuilder.Entity("Lab5.Models.DangKy", b =>
                {
                    b.HasOne("Lab5.Models.HocVien", "HocVien")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab5.Models.LopHoc", "LopHoc")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("Lab5.Models.Day", b =>
                {
                    b.HasOne("Lab5.Models.GiaoVien", "GiaoVien")
                        .WithMany("DanhSachDay")
                        .HasForeignKey("MaGiaoVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab5.Models.LopHoc", "LopHoc")
                        .WithMany("DanhSachDay")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("Lab5.Models.Diem", b =>
                {
                    b.HasOne("Lab5.Models.HocVien", null)
                        .WithMany("DanhSachDiem")
                        .HasForeignKey("HocVienMaHocVien");

                    b.HasOne("Lab5.Models.MonHoc", null)
                        .WithMany("DanhSachDiem")
                        .HasForeignKey("MonHocMaMonHoc");

                    b.HasOne("Lab5.Models.Hoc", "Hoc")
                        .WithMany("DanhSachDiem")
                        .HasForeignKey("MaHocVien", "MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoc");
                });

            modelBuilder.Entity("Lab5.Models.Hoc", b =>
                {
                    b.HasOne("Lab5.Models.HocVien", "HocVien")
                        .WithMany("DanhSachHoc")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab5.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachHoc")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Lab5.Models.LopHoc", b =>
                {
                    b.HasOne("Lab5.Models.GiaoVien", "GiaoVien")
                        .WithMany("DanhSachLopHoc")
                        .HasForeignKey("MaGiaoVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lab5.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DanhSachLopHoc")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab5.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachLopHoc")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Lab5.Models.GiaoVien", b =>
                {
                    b.Navigation("DanhSachDay");

                    b.Navigation("DanhSachLopHoc");
                });

            modelBuilder.Entity("Lab5.Models.Hoc", b =>
                {
                    b.Navigation("DanhSachChungChi");

                    b.Navigation("DanhSachDiem");
                });

            modelBuilder.Entity("Lab5.Models.HocVien", b =>
                {
                    b.Navigation("DanhSachChungChi");

                    b.Navigation("DanhSachDangKy");

                    b.Navigation("DanhSachDiem");

                    b.Navigation("DanhSachHoc");
                });

            modelBuilder.Entity("Lab5.Models.KhoaHoc", b =>
                {
                    b.Navigation("DanhSachLopHoc");
                });

            modelBuilder.Entity("Lab5.Models.LopHoc", b =>
                {
                    b.Navigation("DanhSachDangKy");

                    b.Navigation("DanhSachDay");
                });

            modelBuilder.Entity("Lab5.Models.MonHoc", b =>
                {
                    b.Navigation("DanhSachChungChi");

                    b.Navigation("DanhSachDiem");

                    b.Navigation("DanhSachHoc");

                    b.Navigation("DanhSachLopHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
